# Copyright Ripley 2020
# Cloud Build Pipeline

steps:
  - id: 'Build'
    name: 'maven:3-jdk-8'
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
    #args: ['compile', 'jib:build', '-Dimage=gcr.io/$PROJECT_ID/basketball-api:$BUILD_ID' ]

  - id: 'Create image'
    name: 'gcr.io/cloud-builders/docker'
    args: ["build", "-t", "gcr.io/$PROJECT_ID/basketball-api:$BUILD_ID", "."]

images: ["gcr.io/$PROJECT_ID/basketball-api:$BUILD_ID"]