# Copyright Ripley 2020
# Cloud Build Pipeline

steps:
  - id: 'Pull image'
    name: 'maven:3-jdk-8'
    entrypoint: mvn
    args: ['compile', 'jib:build', '-Dimage=gcr.io/$PROJECT_ID/basketball-api:$BUILD_ID' ]